<a href="https://colab.research.google.com/github/sipocz/CabPrice/blob/B20210507/CabPrice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://github.com/sipocz/CabPrice/raw/B20210507/TRAIN.csv

--2021-05-07 21:23:13--  https://github.com/sipocz/CabPrice/raw/B20210507/TRAIN.csv
Resolving github.com (github.com)... 13.114.40.48
Connecting to github.com (github.com)|13.114.40.48|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/sipocz/CabPrice/B20210507/TRAIN.csv [following]
--2021-05-07 21:23:14--  https://raw.githubusercontent.com/sipocz/CabPrice/B20210507/TRAIN.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7524003 (7.2M) [text/plain]
Saving to: ‘TRAIN.csv’

TRAIN.csv           100%[===================>]   7.17M  21.6MB/s    in 0.3s    

2021-05-07 21:23:15 (21.6 MB/s) - ‘TRAIN.csv’ saved [7524003/7524003]



In [4]:
!head TRAIN.csv

index,time_stamp,cab_provider,source,destination,distance,surge_multiplier,cab_type,fare
0,1543203646318,Lyft,Boston University,Theatre District,3.03,1.0,Lux Black XL,34.0
1,1543203646319,Uber,South Station,Theatre District,1.3,1.0,Black,18.5
2,1543203646320,Uber,Theatre District,Fenway,2.71,1.0,UberX,19.5
3,1543203646320,Lyft,Northeastern University,Beacon Hill,2.43,1.0,Lyft,10.5
4,1543203646320,Uber,Theatre District,Fenway,2.71,1.0,UberXL,32.0
5,1543203646358,Uber,Beacon Hill,North End,2.19,1.0,UberX,8.0
6,1543203646358,Uber,North Station,Fenway,3.05,1.0,WAV,10.5
7,1543203646358,Uber,Beacon Hill,North End,2.19,1.0,UberXL,13.0
8,1543203646358,Uber,Beacon Hill,North End,2.19,1.0,Black,17.5


In [5]:
import pandas as pd

In [7]:
df=pd.read_csv("TRAIN.csv")

In [37]:
df.head(12)
#df.tail(12)

index     time_stamp cab_provider  ... surge_multiplier      cab_type  fare
0       0  1543203646318         Lyft  ...             1.00  Lux Black XL  34.0
1       1  1543203646319         Uber  ...             1.00         Black  18.5
2       2  1543203646320         Uber  ...             1.00         UberX  19.5
3       3  1543203646320         Lyft  ...             1.00          Lyft  10.5
4       4  1543203646320         Uber  ...             1.00        UberXL  32.0
5       5  1543203646358         Uber  ...             1.00         UberX   8.0
6       6  1543203646358         Uber  ...             1.00           WAV  10.5
7       7  1543203646358         Uber  ...             1.00        UberXL  13.0
8       8  1543203646358         Uber  ...             1.00         Black  17.5
9       9  1543203646359         Lyft  ...             1.00        Shared   7.0
10     10  1543203646359         Lyft  ...             1.75           Lux  47.5
11     11  1543203646359         Lyft  ...             1.75     Lux Black  62.5

[12 rows x 9 columns]

In [23]:
a=list(set(df["source"]))

In [25]:
a[0]

'North Station'

In [35]:
import numpy as np 

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

vals = np.array(a)
vals=vals.reshape(-1,1)
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(vals)
print(onehot_encoded)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [31]:
vals

array(['North Station', 'Beacon Hill', 'Back Bay', 'West End', 'Fenway',
       'North End', 'Theatre District', 'Financial District',
       'Haymarket Square', 'South Station', 'Northeastern University',
       'Boston University'], dtype='<U23')

In [54]:
sources=pd.get_dummies(df["source"],prefix='source',drop_first=False)
dest=pd.get_dummies(df["destination"],prefix='dest',drop_first=False)
cab=pd.get_dummies(df["cab_provider"],prefix='provider',drop_first=False)



In [55]:
cab

provider_Lyft  provider_Uber
0                  1              0
1                  0              1
2                  0              1
3                  1              0
4                  0              1
...              ...            ...
99995              0              1
99996              0              1
99997              0              1
99998              0              1
99999              0              1

[100000 rows x 2 columns]

In [56]:
df2=sources.merge(dest, left_on=True)

TypeError: ignored

In [57]:
df2

dest_Back Bay  ...  source_West End
0                NaN  ...              NaN
1                NaN  ...              NaN
2                NaN  ...              NaN
3                NaN  ...              NaN
4                NaN  ...              NaN
...              ...  ...              ...
99995            NaN  ...              NaN
99996            NaN  ...              NaN
99997            NaN  ...              NaN
99998            NaN  ...              NaN
99999            NaN  ...              NaN

[100000 rows x 24 columns]